meta:
    extract_upstream: false

tasks:
    
    - source: scripts/get/txt_to_parquet.py
      upstream: []
      name: txt_to_parquet
      product: 
        nb: product/get/txt_to_parquet.ipynb
        data: product/get/tweets.parquet
      params:
        file_paths: ["data/Cheng-Caverlee-Lee/training_set_tweets.txt", "data/Cheng-Caverlee-Lee/test_set_tweets.txt"]
    
    - source: scripts/get/create_chroma_db.py
      upstream: [txt_to_parquet]
      name: create_chroma_db
      product:
        nb: product/get/create_chroma_db.ipynb
      params:
        chroma_collection: "{{chroma_collection}}"
        reset_collection: "{{reset_collection}}"
        sentence_embedder_id: "{{sentence_embedder_id}}"
        similarity_type: "{{sentence_embedder_similarity}}"
        BATCH_SIZE: 512
        LIMIT: 1000000
    
    # - source: scripts/exploration/explore_tweets.py
    #   upstream: [txt_to_parquet]
    #   product:
    #     nb: product/exploration/explore_tweets.ipynb
    
    # - source: scripts/exploration/rag_tweet.py
    #   upstream: [txt_to_parquet]
    #   name: rag_tweet
    #   product:
    #     nb: scripts/exploration/rag_tweet.ipynb
        
      